language: python
required: sudo
python:
    - "3.4"
virtualenv:
    system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - sudo apt-get install python-tk
  - sudo -H python -m pip install -r requirements.txt
script:
  - python -m nose

