language: python
python:
    "2.7"
required: sudo
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - pip install matplotlib
    - pip install numpy
    - pip install pillow
    - pip install pyinstaller
    - sudo apt-get install python-tk
script:
    - sudo python testing.py
    - pyinstaller main.py
