language: python
python:
    "2.7"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep
    - pip install matplotlib
    - pip install numpy
    - pip install pillow
    - pip install pyinstaller
script:
    - python testing.py
    - pyinstaller main.py
