"""
Dictionary of abilities with all their known effects
"""

ability_to_effects = {
    'Barrel Roll': ['Barrel Roll'],
    'Blaster Overcharge': ['Blaster Overcharge',
                           'Improved Criticals',
                           'Overcharged Damage'],
    'Booster Recharge': ['Booster Recharge'],
    'Burst Laser Cannon': ['Damage'],
    'Bypass': ['Bypass'],
    'Charged Plating': ['Charged Plating'],
    'Cluster Missiles': ['Damage', 'Cluster Missiles'],
    'Combat Command': ['Combat Command'],
    'Concentrated Fire': ['Concentrated Fire'],
    'Concussion Mine': ['Damage', 'Concussion Mine'],
    'Concussion Missile': ['Damage', 'Slowed'],
    'Contamination': ['Damage'],
    'Damage Overcharge': ['Damage Overcharge'],
    'Distortion Field': ['Distortion Field'],
    'EMP Field': ['Accuracy Reduced',
                  'Sensors Jammed',
                  'System Ability Disabled',
                  'Engine Ability Disabled',
                  'Drone Disabled',
                  'Damage',
                  'Missile Lock Immunity',
                  'Shield Ability Disabled'],
    'EMP Missile': ['Drone Disabled',
                    'Damage',
                    'System Ability Disabled',
                    'Engine Ability Disabled',
                    'Shield Ability Disabled'],
    'Engine Overcharge': ['Engine Overcharge'],
    'Feedback Shield': ['Damage', 'Feedback Shield'],
    'Fortress Shield': ['Fortress Shield', 'AbilityDeactivate'],
    'Heavy Laser Cannon': ['Damage'],
    'Hull Cutter': ['Damage'],
    'Hull Resonance': ['Damage'],
    'Hydro Spanner': ['Hydro Spanner', 'Heal'],
    'Hyperspace Beacon': ['Hyperspace Beacon'],
    'Hyperspace Slingshot': ['Hyperspace Slingshot'],
    'In Your Sights': ['In Your Sights'],
    'Interdiction Drive': ['Interdiction Field', 'Interdiction Drive'],
    'Interdiction Field': ['Interdiction Field'],
    'Interdiction Mine': ['Interdiction Mine', 'Interdiction Field', 'Damage'],
    'Interdiction Missile': ['Interdiction Attack', 'Damage'],
    'Interdiction Sentry Drone': ['Interdiction Sentry Drone'],
    'Invulnerable': ['Invulnerable'],
    'Ion Mine': ['Power Regeneration Slowed',
                 'Damage',
                 'Shield Drain',
                 'Ion Mine'],
    'Ion Missile': ['Damage', 'Slowed', 'Regeneration Reduced'],
    'Ion Railgun': ['Damage',
                    'Reactor Disruption',
                    'Engine Disruption',
                    'Ion Railgun'],
    'Koiogran Turn': ['Koiogran Turn', 'Staying on Target'],
    'Laser Cannon': ['Damage'],
    'Light Laser Cannon': ['Damage'],
    'Lingering Damage': ['Damage'],
    'Lingering Effect': ['Lingering Damage'],
    'Melting Hull': ['Damage'],
    'Missile Sentry Drone': ['Missile Sentry Drone'],
    'Nullify': ['Nullify'],
    'Overcharged Shield': ['Overcharged Shield'],
    'Plasma Burn': ['Damage'],
    'Plasma Railgun': ['Plasma Burn', 'Evasion Reduced', 'Armor Reduced'],
    'Plasma Warheads': ['Plasma Warheads', 'Damage'],
    'Power Dive': ['Power Dive'],
    'Proton Torpedo': ['Damage', 'Melting Hull'],
    'Quad Laser Cannon': ['Damage'],
    'Quick-Charge Shield': ['Shield Boost'],
    'Railgun': ['Damage'],
    'Railgun Sentry Drone': ['Railgun Sentry Drone'],
    'Rapid-Fire Laser Cannon': ['Damage'],
    'Remote Slicing': ['Shield Drain',
                       'System Ability Disabled',
                       'Weapon Power Reduced',
                       'Engine Power Reduced',
                       'Engine Ability Disabled'],
    'Repair Drone': ['Ammunition Refill',
                     'Repair Drone',
                     'Heal',
                     'Shield Restoration'],
    'Repair Probes': ['Repair Probes', 'Heal'],
    'Retro Thrusters': ['Retro Thrusters'],
    'Rocket Pod': ['Damage'],
    'Rotational Thrusters': ['Weapon Power Regeneration'],
    'Running Interference': ['Running Interference'],
    'Sabotage Probe': ['Thrusters Disabled',
                       'Hull Cutter',
                       'Engine Ability Disabled',
                       'Power Dampening',
                       'Engine Slowed'],
    'Seeker Mine': ['Damage', 'Seeker Mine'],
    'Seismic Mine': ['Seismic Mine', 'Damage', 'Engine Slowed', 'Hull Resonance'],
    'Selfdamage': ['Damage'],
    'Sensor Beacon': ['Sensor Beacon'],
    'Sensor Beacon Jamming': ['Sensor Beacon Jamming',
                              'Accuracy Reduced',
                              'Sensors Jammed',
                              'Improved Lock On'],
    'Servo Jammer': ['Servo Jammer'],
    'Shield Overcharge': ['Shield Overcharge'],
    'Shield Power Converter': ['Shield Regen Boost'],
    'Shield Projector': ['Shield Projector'],
    "Slicer's Loop": ["Slicer's Loop"],
    'Slug Railgun': ['Damage'],
    'Snap Turn': ['Snap Turn'],
    'Space Exhaustion': ['Contamination', 'Damage'],
    'Suppression': ['Suppression'],
    'Targeting Telemetry': ['Evasion Decrease',
                            'Targeting Telemetry',
                            'Increased Evasion',
                            'Increased Cannon Range'],
    'Tensor Field': ['Tensor Field'],
    'Thermite Torpedo': ['Plasma Burn',
                         'Thermite Armor Corrosion',
                         'Thermite Shield Disruption'],
    'Tutorial': ['Tutorial'],
    'Weapon Overcharge': ['Weapon Overcharge'],
    'Wingman': ['Wingman']
}

effect_to_ability = {
    effect: ability for ability, list in ability_to_effects.items() for effect in list if effect != "Damage"
}
