# Written by RedFantom, Wing Commander of Thranta Squadron,
# Daethyra, Squadron Leader of Thranta Squadron and Sprigellania, Ace of Thranta Squadron
# Thranta Squadron GSF CombatLog Parser, Copyright (C) 2016 by RedFantom, Daethyra and Sprigellania
# All additions are under the copyright of their respective authors
# For license see LICENSE
from pynput.keyboard import Key

keys = {
    Key.esc: "esc",
    Key.f1: "F1",
    Key.f2: "F2",
    Key.f3: "F3",
    Key.f4: "F4",
    Key.f5: "F5",
    Key.f6: "F6",
    Key.f7: "F7",
    Key.f8: "F8",
    Key.f9: "F9",
    Key.f10: "F10",
    Key.f11: "F11",
    Key.f12: "F12",
    Key.alt_l: "lalt",
    Key.alt_r: "ralt",
    Key.backspace: "backspace",
    Key.space: "space",
    Key.ctrl_l: "lctrl",
    Key.ctrl_r: "rctrl",
    Key.caps_lock: "capslock",
    Key.delete: "delete",
    Key.insert: "insert",
    Key.home: "home",
    Key.page_up: "pageup",
    Key.page_down: "pagedown",
    Key.end: "end",
    Key.shift_l: "lshift",
    Key.shift_r: "rshift",
    Key.num_lock: "numlock",
    Key.scroll_lock: "scrolllock",
    Key.tab: "tab",
    Key.cmd_l: "lwin",
    Key.cmd_r: "rwin",
    Key.up: "up",
    Key.down: "down",
    Key.left: "left",
    Key.right: "right",
    Key.enter: "enter",
    Key.menu: "app",
    Key.print_screen: "printscreen",
    Key.pause: "pause"
}
